### ISSUE TITLE
Typescript Refactor

### ISSUE THREAD

**Issue by manoelcfeliciano** [letranloc/draft-js-katex-plugin#15]
Hi guys, are you open to a PR that refactor this library to use Typescript?

Best regards and hope to hear from you soon.

**Comment by tarjei** [comment]
Hi @manoelcfeliciano , thank you for your request!

This would be most welcome. I would suggest that when doing this, consider removing the dependencies on math-quill and math-input to make the component simpler and easier to upgrade.

**Comment by manoelcfeliciano** [comment]
Perfect, @tarjei, will do that. I will open the PR soon. Feel free to close this issue.

**Comment by bryanprimus** [comment]
hi is there any update on this ?
